### ISSUE TITLE
Segfault after Starting a New game in TD

### ISSUE THREAD

**Issue by xcom169** [OmniBlade/CNCData#1]
![image](https://user-images.githubusercontent.com/17802090/128030201-cc53eddb-2055-45fe-a19b-651c35a344b0.png)

/vanillatd
zsh: segmentation fault (core dumped)  ./vanillatd

**Comment by OmniBlade** [comment]
Which data set is this from? You should have a folder for gdi and nod as part of the standard data which you don't appear to have here.
